import 'package:flutter/material.dart';

const List<IconData> kPickableIcons = [
  // Food & Drink
  Icons.shopping_cart,
  Icons.restaurant,
  Icons.coffee,
  Icons.local_bar,
  Icons.fastfood,
  Icons.cake,
  Icons.local_grocery_store,
  Icons.set_meal,
  // Transport
  Icons.directions_car,
  Icons.directions_bus,
  Icons.local_taxi,
  Icons.flight,
  Icons.train,
  Icons.local_gas_station,
  Icons.pedal_bike,
  Icons.two_wheeler,
  // Home & Bills
  Icons.home,
  Icons.apartment,
  Icons.electric_bolt,
  Icons.water_drop,
  Icons.wifi,
  Icons.phone_android,
  Icons.tv,
  Icons.kitchen,
  // Health & Fitness
  Icons.local_hospital,
  Icons.local_pharmacy,
  Icons.health_and_safety,
  Icons.fitness_center,
  Icons.spa,
  Icons.self_improvement,
  // Shopping & Entertainment
  Icons.shopping_bag,
  Icons.movie,
  Icons.sports_esports,
  Icons.music_note,
  Icons.book,
  Icons.palette,
  Icons.camera_alt,
  Icons.sports,
  Icons.beach_access,
  // Finance & Work
  Icons.attach_money,
  Icons.savings,
  Icons.work,
  Icons.school,
  Icons.business,
  Icons.card_giftcard,
  // Family & Other
  Icons.pets,
  Icons.child_care,
  Icons.celebration,
  Icons.travel_explore,
  Icons.receipt_long,
  Icons.more_horiz,
];

const List<Color> kPickableColors = [
  Color(0xFF5F7F8A),
  Color(0xFF6F8392),
  Color(0xFF7C7796),
  Color(0xFF8B7589),
  Color(0xFF8A6F5C),
  Color(0xFF8F7A4F),
  Color(0xFF7B7462),
  Color(0xFF6E8F68),
  Color(0xFF5F8A84),
  Color(0xFF67849A),
  Color(0xFF7F7299),
  Color(0xFF8A7078),
  Color(0xFF9A8652),
  Color(0xFF7A8064),
  Color(0xFF83786C),
  Color(0xFF6E8790),
  Color(0xFF5F7C76),
  Color(0xFF776D8F),
  Color(0xFF8A765F),
  Color(0xFF6B7E9A),
];
