import 'package:flutter/material.dart';

const List<IconData> kPickableIcons = [
  // Food & Drink
  Icons.shopping_cart,
  Icons.restaurant,
  Icons.coffee,
  Icons.local_bar,
  Icons.fastfood,
  Icons.cake,
  Icons.local_grocery_store,
  Icons.set_meal,
  // Transport
  Icons.directions_car,
  Icons.directions_bus,
  Icons.local_taxi,
  Icons.flight,
  Icons.train,
  Icons.local_gas_station,
  Icons.pedal_bike,
  Icons.two_wheeler,
  // Home & Bills
  Icons.home,
  Icons.apartment,
  Icons.electric_bolt,
  Icons.water_drop,
  Icons.wifi,
  Icons.phone_android,
  Icons.tv,
  Icons.kitchen,
  // Health & Fitness
  Icons.local_hospital,
  Icons.local_pharmacy,
  Icons.health_and_safety,
  Icons.fitness_center,
  Icons.spa,
  Icons.self_improvement,
  // Shopping & Entertainment
  Icons.shopping_bag,
  Icons.movie,
  Icons.sports_esports,
  Icons.music_note,
  Icons.book,
  Icons.palette,
  Icons.camera_alt,
  Icons.sports,
  Icons.beach_access,
  // Finance & Work
  Icons.attach_money,
  Icons.savings,
  Icons.work,
  Icons.school,
  Icons.business,
  Icons.card_giftcard,
  // Family & Other
  Icons.pets,
  Icons.child_care,
  Icons.celebration,
  Icons.travel_explore,
  Icons.receipt_long,
  Icons.more_horiz,
];

const List<Color> kPickableColors = [
  Color(0xFF4CAF50),
  Color(0xFF8BC34A),
  Color(0xFF00BCD4),
  Color(0xFF2196F3),
  Color(0xFF3F51B5),
  Color(0xFF673AB7),
  Color(0xFF9C27B0),
  Color(0xFFE91E63),
  Color(0xFFF44336),
  Color(0xFFFF5722),
  Color(0xFFFF9800),
  Color(0xFFFFEB3B),
  Color(0xFF009688),
  Color(0xFF03A9F4),
  Color(0xFF795548),
  Color(0xFF607D8B),
  Color(0xFF37474F),
  Color(0xFF9E9E9E),
  Color(0xFFFF8F00),
  Color(0xFFAD1457),
];
